# Milestone Action
#   @author: hustcer
#   @created: 2024/10/13 18:50:20
# REF:
#   - https://github.com/cli/cli
#   - https://cli.github.com/manual/
#   - https://github.com/actions/runner-images
#   - https://docs.github.com/cn/actions/creating-actions/about-custom-actions
#   - https://docs.github.com/cn/actions/creating-actions/metadata-syntax-for-github-actions
#   - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#   - https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context

name: 'Milestone Action'
author: 'hustcer'
description: 'A github action to set a milestone for a merged PR.'

branding:
  icon: 'bookmark'
  color: 'purple'

inputs:
  force:
    required: false
    default: false
    description: 'If the PR was already assigned to a milestone, force to set a new milestone. Defaults to false.'
  milestone:
    required: false
    default: ''
    description: 'The milestone to set. If not provided, will try to guess a milestone.'
  github-token:
    required: false
    default: '${{ github.token }}'
    description: 'The GITHUB_TOKEN secret or personal access token to authenticate. Defaults to `github.token`.'

runs:
  using: 'composite'
  steps:
    - name: Setup Nu
      uses: hustcer/setup-nu@v3
      with:
        version: '0.98.0'

    - name: Set Milestone
      shell: nu {0}
      run: |
        use ${{ github.action_path }}/nu/milestone.nu *
        let repo = '${{ github.repository }}'
        let token = '${{ inputs.github-token }}'
        let pr = '${{ github.event.pull_request.number }}'
        let force = '${{ inputs.force }}' | into bool
        let milestone = '${{ inputs.milestone }}'
        set-milestone $repo --gh-token $token --pr $pr --force=$force --milestone=$milestone

