# Milestone Action
#   @author: hustcer
#   @created: 2024/10/13 18:50:20
#   Notice:
#     Remember to change settings of the repository and update the Workflow permissions to
#     allow "Read and write permissions"
#     Disable actions and enable it again to make it work. Don't forget to save the changes.
# REF:
#   - https://github.com/cli/cli
#   - https://cli.github.com/manual/
#   - https://github.com/actions/runner-images
#   - https://github.com/orgs/community/discussions/60820
#   - https://docs.github.com/cn/actions/creating-actions/about-custom-actions
#   - https://docs.github.com/cn/actions/creating-actions/metadata-syntax-for-github-actions
#   - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#   - https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context

name: 'Milestone Action'
author: 'hustcer'
description: 'A github action to set a milestone for a merged PR.'

branding:
  icon: 'bookmark'
  color: 'purple'

inputs:
  action:
    required: false
    default: 'bind-pr'
    description: 'The action to perform, should be bind-pr,bind-issue,create or close. Defaults to bind-pr.'
  title:
    required: false
    default: '1.0.0'
    description: 'The title of the milestone to create.'
  description:
    required: false
    default: 'The first milestone.'
    description: 'The description of the milestone to create.'
  due-on:
    required: false
    default: ''
    description: 'The due date of the milestone to create.'
  force:
    required: false
    default: false
    description: 'If the PR was already assigned to a milestone, force to set a new milestone. Defaults to false.'
  milestone:
    required: false
    default: ''
    description: 'The milestone to set. If not provided, will try to guess a milestone.'
  github-token:
    required: false
    default: '${{ github.token }}'
    description: 'The GITHUB_TOKEN secret or personal access token to authenticate. Defaults to `github.token`.'

runs:
  using: 'composite'
  steps:
    - name: Setup Nu
      uses: hustcer/setup-nu@v3
      with:
        version: '0.98.0'

    - name: Set Milestone
      shell: nu {0}
      run: |
        use ${{ github.action_path }}/nu/milestone.nu *
        let action = '${{ inputs.action }}'
        let repo = '${{ github.repository }}'
        let title = '${{ inputs.title }}'
        let dueOn = '${{ inputs.due-on }}'
        let description = '${{ inputs.description }}'
        let token = '${{ inputs.github-token }}'
        let milestone = '${{ inputs.milestone }}'
        let issue = '${{ github.event.issue.number }}'
        let pr = '${{ github.event.pull_request.number }}'
        let force = '${{ inputs.force }}' | into bool
        milestone-action $action $repo --gh-token=$token --force=$force --pr=$pr --issue=$issue --milestone=$milestone --title=$title --description=$description --due-on=$dueOn

