query issueCloser(
  $repo_owner: String!
  $repo_name: String!
  $issue_number: Int!
) {
  repository(owner: $repo_owner, name: $repo_name) {
    issueOrPullRequest(number: $issue_number) {
      __typename
      ... on Closable {
        closed
        closedAt
      }
      ... on Issue {
        timeline(last: 100) {
          edges {
            node {
              ... on ClosedEvent {
                stateReason
                closer {
                  __typename
                  ... on PullRequest {
                    repository {
                      nameWithOwner
                    }
                    title
                    number
                    mergeCommit {
                      abbreviatedOid
                    }
                    milestone {
                      title
                    }
                    author {
                      login
                    }
                  }
                }
                actor {
                  login
                }
              }
            }
          }
        }
      }
    }
  }
}
