query prClosingIssues($repo_owner: String!, $repo_name: String!, $pr_number: Int!) {
  repository(owner: $repo_owner, name: $repo_name) {
    pullRequest(number: $pr_number) {
      number
      title
      milestone {
        title
        number
      }
      closingIssuesReferences(first: 20) {
        edges {
          node {
            number
            title
            state
            milestone {
              title
              number
            }
          }
        }
      }
    }
  }
}

