# Description:
#   - Close a milestone by title or number.

name: Milestone Close@develop
on:
  workflow_dispatch:
    inputs:
      milestone:
        required: true
        description: 'Title / Number'

# Fix GraphQL: Resource not accessible by integration (updatePullRequest)
permissions:
  contents: write
  pull-requests: write

jobs:
  close-milestone:
    runs-on: ubuntu-latest
    name: Close Milestone
    steps:
      - name: Close Milestone
        id: close
        uses: hustcer/milestone-action@develop
        with:
          action: close
          milestone: ${{ github.event.inputs.milestone }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Milestone Number
        if: success()
        shell: nu {0}
        run: |
          print $"The closed milestone number is (ansi p)${{ steps.close.outputs.milestone-number }}(ansi reset)"
