# Description:
#   - Create a milestone by title, description and due date.

name: Milestone Create@develop
on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        description: 'Milestone Title'
      description:
        required: false
        description: 'Milestone Description'
      due-on:
        required: false
        description: 'Milestone Due Date'

# Fix GraphQL: Resource not accessible by integration (updatePullRequest)
permissions:
  contents: write

jobs:
  create-milestone:
    runs-on: ubuntu-latest
    name: Create Milestone
    steps:
      - name: Create Milestone
        id: create
        uses: hustcer/milestone-action@develop
        with:
          action: create
          github-token: ${{ secrets.PAT }}
          title: ${{ github.event.inputs.title }}
          due-on: ${{ github.event.inputs.due-on }}
          description: ${{ github.event.inputs.description }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Milestone Number
        if: success()
        run: |
          echo "The new milestone number is ${{ steps.create.outputs.milestone_number }}"

      - name: Debug Output
        if: failure()
        run: |
          echo "Failed to create milestone"
          echo "Title: ${{ github.event.inputs.title }}"
          echo "Due Date: ${{ github.event.inputs.due-on }}"
          echo "Description: ${{ github.event.inputs.description }}"
