# Description:
#   - Update milestone of a merged PR

name: Milestone Action@Release
on:
  pull_request_target:
    types: [closed]

# Fix GraphQL: Resource not accessible by integration (updatePullRequest)
permissions:
  contents: write

jobs:
  update-milestone:
    runs-on: ubuntu-latest
    name: Milestone Update
    steps:
      - name: Set Milestone
        uses: hustcer/milestone-action@main
        with:
          github-token: ${{ secrets.PAT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
