# Description:
#   - Setup Bend with GitHub Actions
# REF:
#   - https://github.com/marketplace/actions/checkout

name: Milestone Action@Release
on:
  push:
    branches:
      - main

    paths-ignore:
      - '**.md'

jobs:
  setup-bend:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Milestone Action@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Milestone
        uses: hustcer/milestone-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
